/**
 * Internal dependencies
 */

export const REDIRECT_LOADING = 'REDIRECT_LOADING';
export const REDIRECT_LOADED = 'REDIRECT_LOADED';
export const REDIRECT_FAILED = 'REDIRECT_FAILED';
export const REDIRECT_SET_SELECTED = 'REDIRECT_SET_SELECTED';
export const REDIRECT_SET_ALL_SELECTED = 'REDIRECT_SET_ALL_SELECTED';
export const REDIRECT_ITEM_SAVING = 'REDIRECT_ITEM_SAVING';
export const REDIRECT_ITEM_FAILED = 'REDIRECT_ITEM_FAILED';
export const REDIRECT_ITEM_SAVED = 'REDIRECT_ITEM_SAVED';
export const REDIRECT_ADD_TOP = 'REDIRECT_ADD_TOP';
export const REDIRECT_DISPLAY_SET = 'REDIRECT_DISPLAY_SET';
