allowBuilds:
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  core-js-pure: set this to true or false
  fs-ext-extra-prebuilt: set this to true or false
  protobufjs: set this to true or false
  unrs-resolver: set this to true or false
