/**
 * Internal dependencies
 */

export const SETTING_LOAD_START = 'SETTING_LOAD_START';
export const SETTING_LOAD_SUCCESS = 'SETTING_LOAD_SUCCESS';
export const SETTING_LOAD_FAILED = 'SETTING_LOAD_FAILED';
export const SETTING_LOAD_STATUS = 'SETTING_LOAD_STATUS';

export const SETTING_SAVING = 'SETTING_SAVING';
export const SETTING_SAVED = 'SETTING_SAVED';
export const SETTING_SAVE_FAILED = 'SETTING_SAVE_FAILED';

export const SETTING_DATABASE_START = 'SETTING_DATABASE_START';
export const SETTING_DATABASE_FAILED = 'SETTING_DATABASE_FAILED';
export const SETTING_DATABASE_SUCCESS = 'SETTING_DATABASE_SUCCESS';
export const SETTING_DATABASE_FINISH = 'SETTING_DATABASE_FINISH';
export const SETTING_DATABASE_SHOW = 'SETTING_DATABASE_SHOW';

export const SETTING_API_FAILED = 'SETTING_API_FAILED';
export const SETTING_API_SUCCESS = 'SETTING_API_SUCCESS';
export const SETTING_API_TRY = 'SETTING_API_TRY';

export const STATUS_IN_PROGRESS = 'STATUS_IN_PROGRESS';
export const STATUS_FAILED = 'STATUS_FAILED';
export const STATUS_COMPLETE = 'STATUS_COMPLETE';
export const STATUS_SAVING = 'STATUS_SAVING';
