/**
 * Internal dependencies
 */

export const SETTING_LOAD_START = 'SETTING_LOAD_START';
export const SETTING_LOAD_SUCCESS = 'SETTING_LOAD_SUCCESS';
export const SETTING_LOAD_FAILED = 'SETTING_LOAD_FAILED';

export const SETTING_SAVING = 'SETTING_SAVING';
export const SETTING_SAVED = 'SETTING_SAVED';
export const SETTING_SAVE_FAILED = 'SETTING_SAVE_FAILED';

export const STATUS_IN_PROGRESS = 'STATUS_IN_PROGRESS';
export const STATUS_FAILED = 'STATUS_FAILED';
export const STATUS_COMPLETE = 'STATUS_COMPLETE';
