/**
 * Internal dependencies
 */

export const GROUP_LOADING = 'GROUP_LOADING';
export const GROUP_LOADED = 'GROUP_LOADED';
export const GROUP_FAILED = 'GROUP_FAILED';
export const GROUP_SET_SELECTED = 'GROUP_SET_SELECTED';
export const GROUP_SET_ALL_SELECTED = 'GROUP_SET_ALL_SELECTED';
export const GROUP_ITEM_SAVING = 'GROUP_ITEM_SAVING';
export const GROUP_ITEM_FAILED = 'GROUP_ITEM_FAILED';
export const GROUP_ITEM_SAVED = 'GROUP_ITEM_SAVED';
